FROM nginx:1.28.0

#set timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/conf.d/dev.default.conf /etc/nginx/conf.d/default.conf
COPY nginx/fastcgi_params /etc/nginx/fastcgi_params
COPY nginx/mime.types /etc/nginx/mime.types
COPY --chown=www-data:www-data ./unnamed_project/contents/ /var/www/html/
